### ISSUE TITLE
求教一下，多个工具选择时，应该怎么写

### ISSUE THREAD

**Issue by xs818818** [the-seeds/imitater#4]
tools = [
        {
            "type": "function",
            "function": {
                "name": "dialogue",
                "description": "日常对话的提问和回答",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "question": {"type": "string", "description": "日常对话的提问。"}
                    },
                    "required": ["question"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "open_web",
                "description": "控制网页跳转",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string", "description": "网页的名称。"}
                    },
                    "required": ["name"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "refresh_web",
                "description": "更新网页信息",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string", "description": "网页的名称。"},
                        "data_name": {"type": "string", "description": "信息的名称。"}
                    },
                    "required": ["name","data_name"],
                },
            },
        }       
    ]  
这样写好像得不到最终结果，但是其它地方好像也没有[]增加工具

**Comment by hiyouga** [comment]
这种应该可以啊

**Comment by xs818818** [comment]
确实，要加个自动，不是这里有问题
